print("Input")
nama=input    ("Nama     :")
nim= input    ("NIM      :")
paralel= input("paralel  :")
ttl= input    ("ttl      :")
alamat= input ("alamat   :")
hobby= input  ("hobby    :")
no= input     ("No.HP    :")

print()
print("Output")
print(f"Nama      :{nama}")
print(f"NIM       :{paralel}")
print(f"TTL       :{ttl}")
print(f"alamat    :{alamat}")
print(f"hobby     :{hobby}")
print(f"No.HP     :{no}")